//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

seaography::register_entity_modules!([
    cake,
    cake_filling,
    cake_filling_price,
    filling,
    fruit,
    vendor,
    rust_keyword,
    cake_with_float,
    cake_with_double,
    collection,
    collection_float,
    parent,
    child,
]);

seaography::register_active_enums!([
    sea_orm_active_enums::CoinflipResultType,
    sea_orm_active_enums::MediaType,
]);
