// Generated by sea-schema
Schema {
    schema: "bakery",
    system: SystemInfo {
        version: 50726,
        system: "",
        suffix: [],
    },
    tables: [
        TableDef {
            info: TableInfo {
                name: "cake",
                engine: InnoDb,
                auto_increment: Some(
                    3,
                ),
                char_set: Utf8Mb4,
                collation: Utf8Mb4GeneralCi,
                comment: "",
            },
            columns: [
                ColumnInfo {
                    name: "id",
                    col_type: Int(
                        NumericAttr {
                            maximum: Some(
                                11,
                            ),
                            decimal: None,
                            unsigned: None,
                            zero_fill: None,
                        },
                    ),
                    null: false,
                    key: Primary,
                    default: None,
                    extra: ColumnExtra {
                        auto_increment: true,
                        on_update_current_timestamp: false,
                        generated: false,
                        default_generated: false,
                    },
                    expression: None,
                    comment: "",
                },
                ColumnInfo {
                    name: "name",
                    col_type: Varchar(
                        StringAttr {
                            length: Some(
                                255,
                            ),
                            charset: None,
                            collation: None,
                        },
                    ),
                    null: true,
                    key: NotKey,
                    default: None,
                    extra: ColumnExtra {
                        auto_increment: false,
                        on_update_current_timestamp: false,
                        generated: false,
                        default_generated: false,
                    },
                    expression: None,
                    comment: "",
                },
            ],
            indexes: [
                IndexInfo {
                    unique: true,
                    name: "PRIMARY",
                    parts: [
                        IndexPart {
                            column: "id",
                            order: Ascending,
                            sub_part: None,
                        },
                    ],
                    nullable: false,
                    idx_type: BTree,
                    comment: "",
                    functional: false,
                },
            ],
            foreign_keys: [],
        },
        TableDef {
            info: TableInfo {
                name: "cake_filling",
                engine: InnoDb,
                auto_increment: None,
                char_set: Utf8Mb4,
                collation: Utf8Mb4GeneralCi,
                comment: "",
            },
            columns: [
                ColumnInfo {
                    name: "cake_id",
                    col_type: Int(
                        NumericAttr {
                            maximum: Some(
                                11,
                            ),
                            decimal: None,
                            unsigned: None,
                            zero_fill: None,
                        },
                    ),
                    null: false,
                    key: Primary,
                    default: None,
                    extra: ColumnExtra {
                        auto_increment: false,
                        on_update_current_timestamp: false,
                        generated: false,
                        default_generated: false,
                    },
                    expression: None,
                    comment: "",
                },
                ColumnInfo {
                    name: "filling_id",
                    col_type: Int(
                        NumericAttr {
                            maximum: Some(
                                11,
                            ),
                            decimal: None,
                            unsigned: None,
                            zero_fill: None,
                        },
                    ),
                    null: false,
                    key: Primary,
                    default: None,
                    extra: ColumnExtra {
                        auto_increment: false,
                        on_update_current_timestamp: false,
                        generated: false,
                        default_generated: false,
                    },
                    expression: None,
                    comment: "",
                },
            ],
            indexes: [
                IndexInfo {
                    unique: false,
                    name: "filling_id",
                    parts: [
                        IndexPart {
                            column: "filling_id",
                            order: Ascending,
                            sub_part: None,
                        },
                    ],
                    nullable: false,
                    idx_type: BTree,
                    comment: "",
                    functional: false,
                },
                IndexInfo {
                    unique: true,
                    name: "PRIMARY",
                    parts: [
                        IndexPart {
                            column: "cake_id",
                            order: Ascending,
                            sub_part: None,
                        },
                        IndexPart {
                            column: "filling_id",
                            order: Ascending,
                            sub_part: None,
                        },
                    ],
                    nullable: false,
                    idx_type: BTree,
                    comment: "",
                    functional: false,
                },
            ],
            foreign_keys: [
                ForeignKeyInfo {
                    name: "cake_filling_ibfk_1",
                    columns: [
                        "cake_id",
                    ],
                    referenced_table: "cake",
                    referenced_columns: [
                        "id",
                    ],
                    on_update: Restrict,
                    on_delete: Restrict,
                },
                ForeignKeyInfo {
                    name: "cake_filling_ibfk_2",
                    columns: [
                        "filling_id",
                    ],
                    referenced_table: "filling",
                    referenced_columns: [
                        "id",
                    ],
                    on_update: Restrict,
                    on_delete: Restrict,
                },
            ],
        },
        TableDef {
            info: TableInfo {
                name: "filling",
                engine: InnoDb,
                auto_increment: Some(
                    4,
                ),
                char_set: Utf8Mb4,
                collation: Utf8Mb4GeneralCi,
                comment: "",
            },
            columns: [
                ColumnInfo {
                    name: "id",
                    col_type: Int(
                        NumericAttr {
                            maximum: Some(
                                11,
                            ),
                            decimal: None,
                            unsigned: None,
                            zero_fill: None,
                        },
                    ),
                    null: false,
                    key: Primary,
                    default: None,
                    extra: ColumnExtra {
                        auto_increment: true,
                        on_update_current_timestamp: false,
                        generated: false,
                        default_generated: false,
                    },
                    expression: None,
                    comment: "",
                },
                ColumnInfo {
                    name: "name",
                    col_type: Varchar(
                        StringAttr {
                            length: Some(
                                255,
                            ),
                            charset: None,
                            collation: None,
                        },
                    ),
                    null: true,
                    key: NotKey,
                    default: None,
                    extra: ColumnExtra {
                        auto_increment: false,
                        on_update_current_timestamp: false,
                        generated: false,
                        default_generated: false,
                    },
                    expression: None,
                    comment: "",
                },
            ],
            indexes: [
                IndexInfo {
                    unique: true,
                    name: "PRIMARY",
                    parts: [
                        IndexPart {
                            column: "id",
                            order: Ascending,
                            sub_part: None,
                        },
                    ],
                    nullable: false,
                    idx_type: BTree,
                    comment: "",
                    functional: false,
                },
            ],
            foreign_keys: [],
        },
        TableDef {
            info: TableInfo {
                name: "fruit",
                engine: InnoDb,
                auto_increment: Some(
                    41,
                ),
                char_set: Utf8Mb4,
                collation: Utf8Mb4GeneralCi,
                comment: "",
            },
            columns: [
                ColumnInfo {
                    name: "id",
                    col_type: Int(
                        NumericAttr {
                            maximum: Some(
                                11,
                            ),
                            decimal: None,
                            unsigned: None,
                            zero_fill: None,
                        },
                    ),
                    null: false,
                    key: Primary,
                    default: None,
                    extra: ColumnExtra {
                        auto_increment: true,
                        on_update_current_timestamp: false,
                        generated: false,
                        default_generated: false,
                    },
                    expression: None,
                    comment: "",
                },
                ColumnInfo {
                    name: "name",
                    col_type: Varchar(
                        StringAttr {
                            length: Some(
                                255,
                            ),
                            charset: None,
                            collation: None,
                        },
                    ),
                    null: true,
                    key: NotKey,
                    default: None,
                    extra: ColumnExtra {
                        auto_increment: false,
                        on_update_current_timestamp: false,
                        generated: false,
                        default_generated: false,
                    },
                    expression: None,
                    comment: "",
                },
                ColumnInfo {
                    name: "cake_id",
                    col_type: Int(
                        NumericAttr {
                            maximum: Some(
                                11,
                            ),
                            decimal: None,
                            unsigned: None,
                            zero_fill: None,
                        },
                    ),
                    null: true,
                    key: Multiple,
                    default: None,
                    extra: ColumnExtra {
                        auto_increment: false,
                        on_update_current_timestamp: false,
                        generated: false,
                        default_generated: false,
                    },
                    expression: None,
                    comment: "",
                },
            ],
            indexes: [
                IndexInfo {
                    unique: false,
                    name: "cake_id",
                    parts: [
                        IndexPart {
                            column: "cake_id",
                            order: Ascending,
                            sub_part: None,
                        },
                    ],
                    nullable: true,
                    idx_type: BTree,
                    comment: "",
                    functional: false,
                },
                IndexInfo {
                    unique: true,
                    name: "PRIMARY",
                    parts: [
                        IndexPart {
                            column: "id",
                            order: Ascending,
                            sub_part: None,
                        },
                    ],
                    nullable: false,
                    idx_type: BTree,
                    comment: "",
                    functional: false,
                },
            ],
            foreign_keys: [
                ForeignKeyInfo {
                    name: "fruit_ibfk_1",
                    columns: [
                        "cake_id",
                    ],
                    referenced_table: "cake",
                    referenced_columns: [
                        "id",
                    ],
                    on_update: Restrict,
                    on_delete: Restrict,
                },
            ],
        },
    ],
}
