//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "baker")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub contact_details: Json,
    pub bakery_id: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "BakeryId",
        to = "Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub bakery: Option<super::bakery::Entity>,
    #[sea_orm(has_many, via = "cakes_bakers::Baker")]
    pub cakes: Vec<super::cake::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
