//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cakes_bakers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cake_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub baker_id: i32,
    #[sea_orm(relation, from = "BakerId", to = "Id")]
    pub baker: BelongsTo<super::baker::Entity>,
    #[sea_orm(relation, from = "CakeId", to = "Id")]
    pub cake: BelongsTo<super::cake::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
