[package]
name = "core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { path = "../../../", default-features = false }

[dev-dependencies]
sea-orm = { path = "../../../", features = ["mock"] }
