#![allow(unused_imports, dead_code)]

pub mod common;

pub use sea_orm::{DbBackend, DbErr};

// DATABASE_URL=cockroachdb://...:26257/... cargo test --features cockroachdb,sqlx-postgres,runtime-tokio --test cockroachdb_tests
#[sea_orm_macros::test]
#[cfg(feature = "cockroachdb")]
async fn test_cockroachdb_backend_detection() -> Result<(), DbErr> {
    // Test is_prefix_of for various URL schemes
    assert!(DbBackend::Cockroach.is_prefix_of("cockroachdb://localhost:26257/test"));
    assert!(DbBackend::Cockroach.is_prefix_of("postgres://localhost:26257/test"));
    assert!(DbBackend::Cockroach.is_prefix_of("postgresql://localhost:26257/test"));
    assert!(!DbBackend::Cockroach.is_prefix_of("mysql://localhost:3306/test"));
    assert!(!DbBackend::Cockroach.is_prefix_of("sqlite://test.db"));

    // Test as_str
    assert_eq!(DbBackend::Cockroach.as_str(), "Cockroach");

    // Test support_returning
    assert!(DbBackend::Cockroach.support_returning());

    Ok(())
}

#[sea_orm_macros::test]
#[cfg(feature = "cockroachdb")]
async fn test_cockroachdb_schema_identity() -> Result<(), DbErr> {
    use sea_orm::sea_query::{ColumnDef, Alias, PostgresQueryBuilder, Table};

    // Create a table with auto-increment primary key
    let table = Table::create()
        .table(Alias::new("test_table"))
        .col(
            ColumnDef::new(Alias::new("id"))
                .integer()
                .not_null()
                .auto_increment()
                .primary_key(),
        )
        .col(ColumnDef::new(Alias::new("name")).string())
        .to_owned();

    // Build the SQL - should use GENERATED BY DEFAULT AS IDENTITY, not SERIAL
    let sql = table.to_string(PostgresQueryBuilder);

    // CockroachDB uses GENERATED BY DEFAULT AS IDENTITY instead of SERIAL
    assert!(
        sql.contains("GENERATED BY DEFAULT AS IDENTITY"),
        "Expected GENERATED BY DEFAULT AS IDENTITY in schema, got: {sql}"
    );
    assert!(
        !sql.contains("SERIAL"),
        "SERIAL should not be used for CockroachDB, got: {sql}"
    );

    Ok(())
}

#[sea_orm_macros::test]
#[cfg(feature = "cockroachdb")]
async fn test_cockroachdb_boolean_value() -> Result<(), DbErr> {
    use sea_orm::sea_query::Value;

    let true_val = DbBackend::Cockroach.boolean_value(true);
    let false_val = DbBackend::Cockroach.boolean_value(false);

    // Boolean values should be converted correctly
    assert_eq!(true_val, Value::Bool(Some(true)));
    assert_eq!(false_val, Value::Bool(Some(false)));

    Ok(())
}
