//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "_cake_filling_")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cake_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub filling_id: i32,
    #[sea_orm(relation, from = "CakeId", to = "Id", on_update = "Cascade", on_delete = "Cascade")]
    pub cake: BelongsTo<super::cake::Entity> ,
    #[sea_orm(relation, from = "FillingId", to = "Id", on_update = "Cascade", on_delete = "Cascade")]
    pub filling: BelongsTo<super::filling::Entity> ,
}

impl ActiveModelBehavior for ActiveModel {}
