//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cake_with_float")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String> ,
    #[sea_orm(column_type = "Float", nullable)]
    pub price: Option<f32> ,
    #[sea_orm(relation)]
    pub fruits: HasMany<super::fruit::Entity> ,
    #[sea_orm(relation, via = "cake_filling")]
    pub fillings: HasMany<super::filling::Entity> ,
}

impl ActiveModelBehavior for ActiveModel {}
