//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "cake_filling_price")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cake_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub filling_id: i32,
    pub price: Decimal,
    #[sea_orm(
        belongs_to,
        from = "(cake_id, filling_id)",
        to = "(cake_id, filling_id)"
    )]
    pub cake_filling: HasOne<super::cake_filling::Entity> ,
}

impl ActiveModelBehavior for ActiveModel {}