//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cake_with_double")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String> ,
    #[sea_orm(column_type = "Double", nullable)]
    pub price: Option<f64> ,
    #[sea_orm(has_many)]
    pub fruits: HasMany<super::fruit::Entity> ,
    #[sea_orm(has_many, via = "cake_filling")]
    pub fillings: HasMany<super::filling::Entity> ,
}

impl ActiveModelBehavior for ActiveModel {}
