//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "child")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub parent_id1: i32,
    pub parent_id2: i32,
    #[sea_orm(belongs_to, from = "(parent_id1, parent_id2)", to = "(id1, id2)")]
    pub parent: HasOne<super::parent::Entity> ,
}

impl ActiveModelBehavior for ActiveModel {}
