//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "child")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub parent_id1: i32,
    pub parent_id2: i32,
    #[sea_orm(relation, from = "(ParentId1, ParentId2)", to = "(Id1, Id2)")]
    pub parent: BelongsTo<super::parent::Entity> ,
}

impl ActiveModelBehavior for ActiveModel {}
