//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fruit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub cake_id: Option<i32> ,
    #[sea_orm(belongs_to, from = "CakeId", to = "Id")]
    pub cake: HasOne<super::cake::Entity> ,
    #[sea_orm(has_many)]
    pub vendors: Vec<super::vendor::Entity> ,
}

impl ActiveModelBehavior for ActiveModel {}
