//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "parent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id1: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id2: i32,
    #[sea_orm(has_many)]
    pub children: HasMany<super::child::Entity> ,
}

impl ActiveModelBehavior for ActiveModel {}
