//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vendor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "_name_")]
    pub name: String,
    #[sea_orm(column_name = "fruitId")]
    pub fruit_id: Option<i32> ,
    #[sea_orm(belongs_to, from = "FruitId", to = "Id")]
    pub fruit: Option<super::fruit::Entity> ,
}

impl ActiveModelBehavior for ActiveModel {}
