//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.14

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "baker")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub contact: String,
    pub bakery_id: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "bakery_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub bakery: HasOne<super::bakery::Entity>,
    #[sea_orm(has_many, via = "cake_baker")]
    pub cakes: HasMany<super::cake::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
