//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.14

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cake")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Decimal(Some((16, 4)))")]
    pub price: Decimal,
    pub bakery_id: i32,
    pub gluten_free: bool,
    #[sea_orm(
        belongs_to,
        from = "bakery_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub bakery: HasOne<super::bakery::Entity>,
    #[sea_orm(has_many, via = "cake_baker")]
    pub bakers: HasMany<super::baker::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
