//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod baker;
pub mod bakery;
pub mod cake;
pub mod cake_baker;

seaography::register_entity_modules!([baker, bakery, cake, cake_baker,]);
