//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::baker::Entity as Baker;
pub use super::bakery::Entity as Bakery;
pub use super::cake::Entity as Cake;
pub use super::cake_baker::Entity as CakeBaker;
