//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub use super::baker::Entity as Baker;
pub use super::bakery::Entity as Bakery;
pub use super::cake::Entity as Cake;
pub use super::cake_baker::Entity as CakeBaker;
