//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "schema_name", table_name = "imports")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub a: Json,
    pub b: Date,
    pub c: Time,
    pub d: DateTime,
    pub e: DateTimeWithTimeZone,
    pub f: Decimal,
    pub g: Uuid,
    pub h: PgVector,
    pub i: IpNetwork,
    pub j: Vec<Json> ,
    pub k: Vec<Vec<IpNetwork>> ,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
