//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.0-rc.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dest")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub src_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::src::Entity",
        from = "Column::SrcId",
        to = "super::src::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Src,
}

impl Related<super::src::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Src.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
