[workspace]
# A separate workspace

[package]
name = "sea-orm-issues-2376"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { version = "^0.12.0", features = [
    "sqlx-sqlite",
    "runtime-async-std-native-tls",
    "macros",
] }
serde = { version = "1.0.210", features = ["derive"] }
futures = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
sea-orm-macros = "1.0.1"
chrono = "0.4.38"
