//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

pub use super::cake::Model as Cake;
pub use super::cake_filling::Model as CakeFilling;
pub use super::filling::Model as Filling;
pub use super::fruit::Model as Fruit;
pub use super::vendor::Model as Vendor;
