//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, DeriveValueType)]
#[sea_orm(try_from_u64)]
pub struct TaskDependencyPkBlockerTaskId(pub super::task::TaskPk);

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, DeriveValueType)]
#[sea_orm(try_from_u64)]
pub struct TaskDependencyPkBlockedTaskId(pub super::task::TaskPk);

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "task_dependency")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blocker_task_id: TaskDependencyPkBlockerTaskId,
    #[sea_orm(primary_key, auto_increment = false)]
    pub blocked_task_id: TaskDependencyPkBlockedTaskId,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::task::Entity",
        from = "Column::BlockedTaskId",
        to = "super::task::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Task2,
    #[sea_orm(
        belongs_to = "super::task::Entity",
        from = "Column::BlockerTaskId",
        to = "super::task::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Task1,
}

impl ActiveModelBehavior for ActiveModel {}
