//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9
// DATABASE_URL=sqlite://bakery.db cargo run --manifest-path sea-orm-cli/Cargo.toml -- generate entity --output-dir tests/common/bakery_dense --entity-format dense

pub mod prelude;

pub mod baker;
pub mod bakery;
pub mod cake;
pub mod cakes_bakers;
pub mod customer;
pub mod lineitem;
pub mod order;
