//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "customer"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub customer_id: i32,
    pub store_id: i32,
    pub first_name: String,
    pub last_name: String,
    pub email: Option<String>,
    pub address_id: i32,
    pub active: String,
    pub create_date: DateTime,
    pub last_update: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    CustomerId,
    StoreId,
    FirstName,
    LastName,
    Email,
    AddressId,
    Active,
    CreateDate,
    LastUpdate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    CustomerId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Address,
    Store,
    Payment,
    Rental,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::CustomerId => ColumnType::Integer.def(),
            Self::StoreId => ColumnType::Integer.def(),
            Self::FirstName => ColumnType::String(None).def(),
            Self::LastName => ColumnType::String(None).def(),
            Self::Email => ColumnType::String(None).def().null(),
            Self::AddressId => ColumnType::Integer.def(),
            Self::Active => ColumnType::Custom("BLOB".to_owned()).def(),
            Self::CreateDate => ColumnType::Timestamp.def(),
            Self::LastUpdate => ColumnType::Timestamp.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Address => Entity::belongs_to(super::address::Entity)
                .from(Column::AddressId)
                .to(super::address::Column::AddressId)
                .into(),
            Self::Store => Entity::belongs_to(super::store::Entity)
                .from(Column::StoreId)
                .to(super::store::Column::StoreId)
                .into(),
            Self::Payment => Entity::has_many(super::payment::Entity).into(),
            Self::Rental => Entity::has_many(super::rental::Entity).into(),
        }
    }
}

impl Related<super::address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Address.def()
    }
}

impl Related<super::store::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl Related<super::payment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payment.def()
    }
}

impl Related<super::rental::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rental.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
