//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "film"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub film_id: i32,
    pub title: String,
    pub description: Option<String>,
    pub release_year: Option<String>,
    pub language_id: String,
    pub original_language_id: Option<String>,
    pub rental_duration: String,
    pub rental_rate: Decimal,
    pub length: Option<String>,
    pub replacement_cost: Decimal,
    pub rating: Option<String>,
    pub special_features: Option<String>,
    pub last_update: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    FilmId,
    Title,
    Description,
    ReleaseYear,
    LanguageId,
    OriginalLanguageId,
    RentalDuration,
    RentalRate,
    Length,
    ReplacementCost,
    Rating,
    SpecialFeatures,
    LastUpdate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    FilmId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Language2,
    Language1,
    FilmActor,
    FilmCategory,
    Inventory,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::FilmId => ColumnType::Integer.def(),
            Self::Title => ColumnType::String(None).def(),
            Self::Description => ColumnType::Custom("BLOB".to_owned()).def().null(),
            Self::ReleaseYear => ColumnType::String(None).def().null(),
            Self::LanguageId => ColumnType::Custom("BLOB".to_owned()).def(),
            Self::OriginalLanguageId => ColumnType::Custom("BLOB".to_owned()).def().null(),
            Self::RentalDuration => ColumnType::Custom("BLOB".to_owned()).def(),
            Self::RentalRate => ColumnType::Decimal(Some((4u32, 2u32))).def(),
            Self::Length => ColumnType::Custom("BLOB".to_owned()).def().null(),
            Self::ReplacementCost => ColumnType::Decimal(Some((5u32, 2u32))).def(),
            Self::Rating => ColumnType::String(None).def().null(),
            Self::SpecialFeatures => ColumnType::String(None).def().null(),
            Self::LastUpdate => ColumnType::Timestamp.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Language2 => Entity::belongs_to(super::language::Entity)
                .from(Column::OriginalLanguageId)
                .to(super::language::Column::LanguageId)
                .into(),
            Self::Language1 => Entity::belongs_to(super::language::Entity)
                .from(Column::LanguageId)
                .to(super::language::Column::LanguageId)
                .into(),
            Self::FilmActor => Entity::has_many(super::film_actor::Entity).into(),
            Self::FilmCategory => Entity::has_many(super::film_category::Entity).into(),
            Self::Inventory => Entity::has_many(super::inventory::Entity).into(),
        }
    }
}

impl Related<super::film_actor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FilmActor.def()
    }
}

impl Related<super::film_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FilmCategory.def()
    }
}

impl Related<super::inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Inventory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
