//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

use chrono::{NaiveDate as Date, NaiveTime as Time, NaiveDateTime as DateTime};
use serde_json::Value as Json;
use rust_decimal::Decimal;
use uuid::Uuid;
use pgvector::Vector as PgVector;
use ipnetwork::IpNetwork;
type DateTimeWithTimeZone = chrono::DateTime<chrono::FixedOffset> ;

#[derive(Clone, Debug, PartialEq)]
pub struct Model {
    #[serde(skip_deserializing)]
    pub a: Json,
    pub b: Date,
    pub c: Time,
    pub d: DateTime,
    pub e: DateTimeWithTimeZone,
    pub f: Decimal,
    pub g: Uuid,
    pub h: PgVector,
    pub i: IpNetwork,
    pub j: Vec<Json> ,
    pub k: Vec<Vec<IpNetwork>> ,
}

