[package]
name = "sea-orm-proxy-wasmtime-example-module"
version = "0.1.0"
authors = ["Langyo <langyo.china@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
ron = "0.8"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
async-std = { version = "1", features = ["attributes", "tokio1"] }

sea-orm = { path = "../../../", default-features = false, features = [
  "macros",
  "proxy",
  "runtime-async-std",
] }
