[package]
name = "sea-orm-proxy-wasmtime-example-module"
version = "0.1.0"
authors = ["Langyo <langyo.china@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
ron = "0.8"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
tokio_wasi = { version = "1", features = ["full"] }

sea-orm = { path = "../../../", default-features = false, features = [
  "macros",
  "proxy",
  "runtime-tokio",
] }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = "abort"
