[package]
name = "module"
version = "0.1.0"
authors = ["Langyo <langyo.china@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
tokio_wasi = { version = "1", features = ["full"] }

sea-orm = { path = "../../../", features = ["proxy", "runtime-tokio"] }
