// Generated by sea-orm-migration v2.0.2
// Generated at: 2026-08-16 15:49:40 UTC
// Backend: PostgreSQL
// Changes:
//   - Created schema: test
//   - Created table: test.person
//   - Created table: post
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();
        db.execute_unprepared(r#"CREATE SCHEMA IF NOT EXISTS "test""#).await?;
        db.execute_unprepared(r#"CREATE TABLE "test"."person" ( "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, "first_name" varchar NOT NULL, "last_name" varchar NOT NULL, "gender" text NOT NULL )"#).await?;
        db.execute_unprepared(r#"CREATE TABLE "post" ( "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, "name" varchar NOT NULL, "text" text NOT NULL )"#).await?;
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        // TODO: implement down migration
        todo!()
    }
}
