//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

pub mod prelude;

pub mod actor;
pub mod address;
pub mod category;
pub mod city;
pub mod country;
pub mod customer;
pub mod film;
pub mod film_actor;
pub mod film_category;
pub mod film_text;
pub mod inventory;
pub mod language;
pub mod payment;
pub mod rental;
pub mod staff;
pub mod store;
