//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

pub use super::actor::Entity as Actor;
pub use super::address::Entity as Address;
pub use super::category::Entity as Category;
pub use super::city::Entity as City;
pub use super::country::Entity as Country;
pub use super::customer::Entity as Customer;
pub use super::film::Entity as Film;
pub use super::film_actor::Entity as FilmActor;
pub use super::film_category::Entity as FilmCategory;
pub use super::film_text::Entity as FilmText;
pub use super::inventory::Entity as Inventory;
pub use super::language::Entity as Language;
pub use super::payment::Entity as Payment;
pub use super::rental::Entity as Rental;
pub use super::staff::Entity as Staff;
pub use super::store::Entity as Store;
