[workspace]
# A separate workspace

[package]
name = "sea-orm-issues-323"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "^1", features = ["derive"] }
sea-orm = { path = "../../", features = [ "sqlx-mysql", "runtime-async-std-native-tls" ]}
