[package]
name = "issue"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "=1.1.15", features = [
  "macros",
  "runtime-tokio-rustls",
  "sqlx-postgres",
] }
tokio = { version = "~1.46", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
