//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

#[derive(Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Model {
    pub id: i32,
    pub name: Option<String> ,
}