//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Model {
    pub id: i32,
    pub integers: Vec<i32> ,
    pub integers_opt: Option<Vec<i32> > ,
}