//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

#[derive(Clone, Debug, PartialEq)]
pub struct Model {
    pub a: Json,
    pub b: Date,
    pub c: Time,
    pub d: DateTime,
    pub e: DateTimeWithTimeZone,
    pub f: Decimal,
    pub g: Uuid,
    pub h: PgVector,
    pub i: IpNetwork,
    pub j: Vec<Json> ,
    pub k: Vec<Vec<IpNetwork>> ,
}
