//! SeaORM Entity. Generated by sea-orm-codegen 0.1.0

pub use super::cake::Model as CakeModel;
pub use super::cake_filling::Model as CakeFillingModel;
pub use super::filling::Model as FillingModel;
pub use super::fruit::Model as FruitModel;
pub use super::vendor::Model as VendorModel;
