use sea_orm::Statement;

pub struct MigrationMetadata<'a> {
    pub version: &'a str,
    pub generated_at: &'a str,
    pub backend: &'a str,
    pub changes: &'a [String],
}

/// Render a complete migration `.rs` file from a list of SQL statements.
pub fn render_migration_file(stmts: &[Statement], meta: &MigrationMetadata<'_>) -> String {
    let comment_header = render_comment_header(meta);
    let up_body = render_up_body(stmts);

    format!(
        r#"{comment_header}
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {{
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {{
        let db = manager.get_connection();
{up_body}
        Ok(())
    }}

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {{
        // TODO: implement down migration
        todo!()
    }}
}}
"#
    )
}

/// Comments the header of the migration file, including version, timestamp, backend, and changes.
fn render_comment_header(meta: &MigrationMetadata<'_>) -> String {
    let mut lines = vec![
        format!("// Generated by sea-orm-entity v{}", meta.version),
        format!("// Generated at: {}", meta.generated_at),
        format!("// Backend: {}", meta.backend),
        "// Changes:".to_string(),
    ];
    lines.extend(meta.changes.iter().map(|c| format!("//   - {c}")));
    lines.join("\n")
}

/// Renders the body of the up migration
fn render_up_body(stmts: &[Statement]) -> String {
    // Just in case. I don't want to deal with this rn
    stmts
        .iter()
        .map(|stmt| {
            if stmt.values.is_some() {
                let sql = stmt.sql.replace('\\', r"\\").replace('"', r#"\""#);
                format!(r#"        db.execute_unprepared("{sql}").await?;"#)
            } else {
                format!("        db.execute_unprepared(r#\"{}\"#).await?;", stmt.sql)
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}
